language: c
compiler:
  - gcc
  - clang
os:
  - linux
  - osx
sudo: false
# Change this to your needs
script: aclocal -I m4 && autoconf && automake --foreign --add-missing && ./configure --prefix=/tmp/hebcal && make all install check
